version: 3

tasks:
  default:
    desc: "The default task"
    deps: ["pre"]
    cmds:
      - task: run:serve
  pre:
    run: once
    cmds:
      - clear || true
  test:
    deps: [pre]
    cmds:
      - go test . -v
  serve:
    desc: "Run the entrypoint server"
    deps: [pre]
    cmds:
      - go run ./cmd/fc-entrypoint serve
  build:
    desc: "Build the entrypoint binary"
    deps: [pre]
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./data/fc-entrypoint ./cmd/fc-entrypoint
  tunnel:
    desc: "Run the SSH tunnel client"
    deps: [pre]
    cmds:
      - go run ./cmd/fc-entrypoint-tunnel {{.CLI_ARGS}}
  build:tunnel:
    desc: "Build the tunnel client binary"
    deps: [pre]
    cmds:
      - CGO_ENABLED=0 go build -o ./data/fc-entrypoint-tunnel ./cmd/fc-entrypoint-tunnel
      - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./data/fc-entrypoint-tunnel.exe ./cmd/fc-entrypoint-tunnel
