name: Build and Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Install go-task
        uses: arduino/setup-task@v2
        with:
          version: 3

      - name: Build
        run: task build

      - name: Make executable
        run: chmod +x data/fc-entrypoint

      - name: Create tag
        run: git tag ${{ github.sha }}

      - name: Push tag
        run: git push origin ${{ github.sha }}

      - name: Upload Release
        run: |
          gh release create ${{ github.sha }} --title "Release ${{ github.sha }}" --generate-notes data/fc-entrypoint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
